
version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    configs:
      - source: prometheus_cfg
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mon_net
    restart: unless-stopped

configs:
  prometheus_cfg:
    file: ./prometheus.yml

networks:
  mon_net:
    external: true

