version: "3.9"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "0"
    environment:
      - TZ=${TZ:-America/Argentina/Buenos_Aires}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
    ports:
      - "3000:3000"
    networks:
      - mon_net
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/grafana
      # - ./provisioning:/etc/grafana/provisioning:ro

networks:
  mon_net:
    external: true
